const defaultUser = {uid:'qa-user',displayName:'Estudiante de prueba',email:'prueba@example.com'};
const initial = window.__qpFixture || {};
let user = initial.guest ? null : JSON.parse(localStorage.getItem('qa-user') || 'null') || defaultUser;
if(localStorage.getItem('qa-logged-out'))user=null;
const authListeners = new Set(), dataListeners = new Set();
const data = JSON.parse(localStorage.getItem('qa-data') || 'null') || initial.data || {};
let auth = {currentUser:user};
function snapshot(value) {return {exists:()=>value!=null,val:()=>structuredClone(value ?? null)};}
function read(path){return path.split('/').filter(Boolean).reduce((v,k)=>v?.[k],data) ?? null;}
function write(path,value){const keys=path.split('/').filter(Boolean);let obj=data;for(const k of keys.slice(0,-1))obj=obj[k] ??= {};if(value===null)delete obj[keys.at(-1)];else obj[keys.at(-1)]=structuredClone(value);localStorage.setItem('qa-data',JSON.stringify(data));for(const l of dataListeners)l.callback(snapshot(read(l.path)));}
function signed(value){user=value;auth.currentUser=value;if(value){localStorage.removeItem('qa-logged-out');localStorage.setItem('qa-user',JSON.stringify(value));}else{localStorage.removeItem('qa-user');localStorage.setItem('qa-logged-out','true');}authListeners.forEach(fn=>fn(value));}
const api={auth,db:{},ref:(_,path)=>path,get:async path=>{if(window.__failGet)throw Error('network');return snapshot(read(path));},set:async(path,value)=>{if(window.__failWrite)throw {code:'PERMISSION_DENIED'};write(path,value);},update:async(path,value)=>{if(window.__failWrite)throw {code:'PERMISSION_DENIED'};write(path,{...read(path),...value});},runTransaction:async(path,change)=>{if(window.__failWrite)throw {code:'PERMISSION_DENIED'};const value=change(structuredClone(read(path)));if(value===undefined)return {committed:false,snapshot:snapshot(read(path))};write(path,value);return {committed:true,snapshot:snapshot(value)};},onValue:(path,callback,error)=>{const l={path,callback};dataListeners.add(l);queueMicrotask(()=>callback(snapshot(read(path))));return()=>dataListeners.delete(l);},onAuthStateChanged:(_,callback)=>{authListeners.add(callback);queueMicrotask(()=>callback(user));return()=>authListeners.delete(callback);},signOut:async()=>signed(null),signInWithEmailAndPassword:async(_,email,password)=>{if(password==='incorrecta')throw {code:'auth/invalid-credential'};signed({...defaultUser,email});return{user};},createUserWithEmailAndPassword:async(_,email)=>{signed({...defaultUser,email});return{user};},updateProfile:async(user,changes)=>{Object.assign(user,changes);},verifyBeforeUpdateEmail:async(user,email)=>{window.__verificationEmail=email;},GoogleAuthProvider:class{},signInWithPopup:async()=>{signed({...defaultUser});return{user};}};
export async function getBackend(){return api;}
